# Generated by Django 4.2.11 on 2024-05-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cooking_time',
            field=models.IntegerField(default=0),
        ),
    ]
